<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // প্রথমে পুরানো ডাটা ডিলিট করুন (ঐচ্ছিক)
        // Setting::truncate();

        $settings = [
            // =============================================
            // ১. GENERAL SETTINGS (সাধারণ সেটিংস)
            // =============================================
            [
                'key'         => 'company_name',
                'value'       => 'হেজবুত তওহীদ',
                'label'       => 'কোম্পানির নাম',
                'type'        => 'text',
                'group'       => 'general',
                'placeholder' => 'আপনার কোম্পানির নাম লিখুন',
                'help_text'   => 'ওয়েবসাইটের সর্বত্র এই নাম দেখাবে',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_tagline',
                'value'       => 'আপনার বিশ্বস্ত অনলাইন সুপারশপ',
                'label'       => 'কোম্পানির ট্যাগলাইন',
                'type'        => 'text',
                'group'       => 'general',
                'placeholder' => 'যেমন: আপনার বিশ্বস্ত অনলাইন শপ',
                'help_text'   => 'কোম্পানির স্লোগান বা ট্যাগলাইন',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_description',
                'value'       => 'হেজবুত তওহীদ - দেশের সবচেয়ে বিশ্বস্ত অনলাইন সুপারশপ। তাজা পণ্য, সেরা দাম এবং দ্রুত ডেলিভারি।',
                'label'       => 'কোম্পানির বিবরণ',
                'type'        => 'textarea',
                'group'       => 'general',
                'placeholder' => 'কোম্পানি সম্পর্কে সংক্ষিপ্ত বিবরণ',
                'help_text'   => 'হোমপেজ ও ফুটারে দেখাবে',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_address',
                'value'       => 'বগুড়া সদর, বগুড়া, বাংলাদেশ',
                'label'       => 'কোম্পানির ঠিকানা',
                'type'        => 'textarea',
                'group'       => 'general',
                'placeholder' => 'পূর্ণ ঠিকানা লিখুন',
                'help_text'   => 'আপনার কোম্পানির ভৌত ঠিকানা',
                'sort_order'  => 4,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_phone',
                'value'       => '+৮৮০ ১৭১২-৩৪৫৬৭৮',
                'label'       => 'ফোন নম্বর',
                'type'        => 'text',
                'group'       => 'general',
                'placeholder' => '+৮৮০ ১XXX-XXXXXXX',
                'help_text'   => 'প্রধান যোগাযোগের নম্বর',
                'sort_order'  => 5,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_hotline',
                'value'       => '০৯৬১২-৩৪৫৬৭৮',
                'label'       => 'হটলাইন নম্বর',
                'type'        => 'text',
                'group'       => 'general',
                'placeholder' => '০৯৬XX-XXXXXXX',
                'help_text'   => '২৪/৭ হটলাইন নম্বর',
                'sort_order'  => 6,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_whatsapp',
                'value'       => '+৮৮০ ১৭১২-৩৪৫৬৭৮',
                'label'       => 'WhatsApp নম্বর',
                'type'        => 'text',
                'group'       => 'general',
                'placeholder' => '+৮৮০ ১XXX-XXXXXXX',
                'help_text'   => 'WhatsApp যোগাযোগের নম্বর',
                'sort_order'  => 7,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_email',
                'value'       => 'info@hezbuttawheed.org',
                'label'       => 'ইমেইল ঠিকানা',
                'type'        => 'email',
                'group'       => 'general',
                'placeholder' => 'info@yourcompany.com',
                'help_text'   => 'প্রধান ইমেইল ঠিকানা',
                'sort_order'  => 8,
                'is_active'   => true,
            ],
            [
                'key'         => 'support_email',
                'value'       => 'support@hezbuttawheed.org',
                'label'       => 'সাপোর্ট ইমেইল',
                'type'        => 'email',
                'group'       => 'general',
                'placeholder' => 'support@yourcompany.com',
                'help_text'   => 'গ্রাহক সাপোর্টের জন্য ইমেইল',
                'sort_order'  => 9,
                'is_active'   => true,
            ],
            [
                'key'         => 'working_hours',
                'value'       => 'সকাল ৮:০০ - রাত ১০:০০ (শনিবার - বৃহস্পতিবার)',
                'label'       => 'কাজের সময়',
                'type'        => 'text',
                'group'       => 'general',
                'placeholder' => 'সকাল ৮টা - রাত ১০টা',
                'help_text'   => 'কোম্পানির কার্যক্রমের সময়',
                'sort_order'  => 10,
                'is_active'   => true,
            ],
            [
                'key'         => 'android_app_file',
                'value'       => null,
                'label'         => 'অ্যান্ড্রয়েড অ্যাপ ফাইল (.apk)',
                'type'        => 'file',
                'group'       => 'general',
                'placeholder' => 'APK ফাইল আপলোড করুন',
                'help_text'   => 'ডাউনলোড করার জন্য অ্যান্ড্রয়েড অ্যাপ (.apk) ফাইলটি এখানে আপলোড করুন।',
                'sort_order'  => 11,
                'is_active'   => true,
            ],
            [
                'key'         => 'ios_app_file',
                'value'       => null,
                'label'         => 'iOS অ্যাপ ফাইল',
                'type'        => 'file',
                'group'       => 'general',
                'placeholder' => 'ফাইল আপলোড করুন',
                'help_text'   => 'ডাউনলোড করার জন্য iOS অ্যাপ ফাইলটি এখানে আপলোড করুন।',
                'sort_order'  => 12,
                'is_active'   => true,
            ],

            // =============================================
            // ২. LOGO & FAVICON SETTINGS
            // =============================================
            [
                'key'         => 'company_logo',
                'value'       => null,
                'label'       => 'কোম্পানির লোগো',
                'type'        => 'image',
                'group'       => 'logo',
                'placeholder' => 'লোগো আপলোড করুন',
                'help_text'   => 'প্রস্তাবিত সাইজ: 200x60px। JPG, PNG, WEBP (সর্বোচ্চ 2MB)',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'favicon',
                'value'       => null,
                'label'       => 'ফেভিকন',
                'type'        => 'image',
                'group'       => 'logo',
                'placeholder' => 'ফেভিকন আপলোড করুন',
                'help_text'   => 'প্রস্তাবিত সাইজ: 32x32px। ICO, PNG (সর্বোচ্চ 1MB)',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'invoice_logo',
                'value'       => null,
                'label'       => 'ইনভয়েস লোগো',
                'type'        => 'image',
                'group'       => 'logo',
                'placeholder' => 'ইনভয়েসের জন্য আলাদা লোগো',
                'help_text'   => 'ইনভয়েসে ব্যবহারের জন্য আলাদা লোগো (ঐচ্ছিক)',
                'sort_order'  => 3,
                'is_active'   => true,
            ],

            // =============================================
            // ৩. SOCIAL MEDIA SETTINGS
            // =============================================
            [
                'key'         => 'facebook_url',
                'value'       => 'https://facebook.com/hezbuttawheed',
                'label'       => 'ফেসবুক',
                'type'        => 'url',
                'group'       => 'social',
                'placeholder' => 'https://facebook.com/your-page',
                'help_text'   => 'আপনার ফেসবুক পেইজের লিংক',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'twitter_url',
                'value'       => 'https://twitter.com/hezbuttawheed',
                'label'       => 'টুইটার (X)',
                'type'        => 'url',
                'group'       => 'social',
                'placeholder' => 'https://twitter.com/your-handle',
                'help_text'   => 'আপনার টুইটার প্রোফাইলের লিংক',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'instagram_url',
                'value'       => 'https://instagram.com/hezbuttawheed',
                'label'       => 'ইনস্টাগ্রাম',
                'type'        => 'url',
                'group'       => 'social',
                'placeholder' => 'https://instagram.com/your-profile',
                'help_text'   => 'আপনার ইনস্টাগ্রাম প্রোফাইলের লিংক',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'linkedin_url',
                'value'       => 'https://linkedin.com/company/hezbuttawheed',
                'label'       => 'লিংকডইন',
                'type'        => 'url',
                'group'       => 'social',
                'placeholder' => 'https://linkedin.com/company/your-company',
                'help_text'   => 'আপনার লিংকডইন কোম্পানি পেইজের লিংক',
                'sort_order'  => 4,
                'is_active'   => true,
            ],
            [
                'key'         => 'youtube_url',
                'value'       => 'https://youtube.com/@hezbuttawheed',
                'label'       => 'ইউটিউব',
                'type'        => 'url',
                'group'       => 'social',
                'placeholder' => 'https://youtube.com/@your-channel',
                'help_text'   => 'আপনার ইউটিউব চ্যানেলের লিংক',
                'sort_order'  => 5,
                'is_active'   => true,
            ],
            [
                'key'         => 'pinterest_url',
                'value'       => null,
                'label'       => 'পিন্টারেস্ট',
                'type'        => 'url',
                'group'       => 'social',
                'placeholder' => 'https://pinterest.com/your-board',
                'help_text'   => 'আপনার পিন্টারেস্ট বোর্ডের লিংক',
                'sort_order'  => 6,
                'is_active'   => true,
            ],
            [
                'key'         => 'tiktok_url',
                'value'       => null,
                'label'       => 'টিকটক',
                'type'        => 'url',
                'group'       => 'social',
                'placeholder' => 'https://tiktok.com/@your-profile',
                'help_text'   => 'আপনার টিকটক প্রোফাইলের লিংক',
                'sort_order'  => 7,
                'is_active'   => true,
            ],

            // =============================================
            // ৪. SEO SETTINGS
            // =============================================
            [
                'key'         => 'site_name',
                'value'       => 'হেজবুত তওহীদ',
                'label'       => 'সাইটের নাম',
                'type'        => 'text',
                'group'       => 'seo',
                'placeholder' => 'আপনার সাইটের নাম',
                'help_text'   => 'সার্চ ইঞ্জিনে এই নাম দেখাবে',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'site_title',
                'value'       => 'হেজবুত তওহীদ - বাংলাদেশের সেরা অনলাইন সুপারশপ',
                'label'       => 'সাইট টাইটেল',
                'type'        => 'text',
                'group'       => 'seo',
                'placeholder' => 'সাইটের টাইটেল (সর্বোচ্চ ৬০ অক্ষর)',
                'help_text'   => 'SEO-এর জন্য গুরুত্বপূর্ণ',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'meta_description',
                'value'       => 'হেজবুত তওহীদে স্বাগতম। তাজা পণ্য, সেরা দাম এবং দ্রুত ডেলিভারি। আমরা ইলেকট্রনিক্স, ফ্যাশন, হোম অ্যান্ড লিভিং প্রোডাক্ট সরবরাহ করি।',
                'label'       => 'মেটা বিবরণ',
                'type'        => 'textarea',
                'group'       => 'seo',
                'placeholder' => 'ওয়েবসাইটের বিবরণ (সর্বোচ্চ ১৬০ অক্ষর)',
                'help_text'   => 'সার্চ রেজাল্টে এই বিবরণ দেখাবে',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'meta_keywords',
                'value'       => 'হেজবুত তওহীদ, অনলাইন শপ, ইলেকট্রনিক্স, ফ্যাশন, হোম অ্যান্ড লিভিং, বাংলাদেশ',
                'label'       => 'মেটা কীওয়ার্ড',
                'type'        => 'text',
                'group'       => 'seo',
                'placeholder' => 'কীওয়ার্ড1, কীওয়ার্ড2, কীওয়ার্ড3',
                'help_text'   => 'কমা দিয়ে কীওয়ার্ড আলাদা করুন',
                'sort_order'  => 4,
                'is_active'   => true,
            ],
            [
                'key'         => 'google_analytics_id',
                'value'       => null,
                'label'       => 'Google Analytics ট্র্যাকিং আইডি',
                'type'        => 'text',
                'group'       => 'seo',
                'placeholder' => 'G-XXXXXXXXXX',
                'help_text'   => 'আপনার Google Analytics 4 ট্র্যাকিং আইডি (GA4)',
                'sort_order'  => 5,
                'is_active'   => true,
            ],
            [
                'key'         => 'google_tag_manager',
                'value'       => null,
                'label'       => 'Google Tag Manager',
                'type'        => 'text',
                'group'       => 'seo',
                'placeholder' => 'GTM-XXXXXX',
                'help_text'   => 'আপনার Google Tag Manager কন্টেইনার আইডি',
                'sort_order'  => 6,
                'is_active'   => true,
            ],
            [
                'key'         => 'facebook_pixel_id',
                'value'       => null,
                'label'       => 'Facebook Pixel ID',
                'type'        => 'text',
                'group'       => 'seo',
                'placeholder' => '১২৩৪৫৬৭৮৯০১২৩৪৫',
                'help_text'   => 'আপনার Facebook Pixel আইডি',
                'sort_order'  => 7,
                'is_active'   => true,
            ],

            // =============================================
            // ৫. CURRENCY SETTINGS
            // =============================================
            [
                'key'         => 'currency_symbol',
                'value'       => '৳',
                'label'       => 'কারেন্সি সিম্বল',
                'type'        => 'text',
                'group'       => 'currency',
                'placeholder' => '৳, $, €',
                'help_text'   => 'আপনার দোকানের মুদ্রার চিহ্ন',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'     => 'currency_position',
                'value'   => 'left',
                'label'   => 'কারেন্সি পজিশন',
                'type'    => 'select',
                'group'   => 'currency',
                'options' => json_encode([
                    'left'        => 'বামে (৳১০০)',
                    'right'       => 'ডানে (১০০৳)',
                    'left_space'  => 'বামে স্পেস সহ (৳ ১০০)',
                    'right_space' => 'ডানে স্পেস সহ (১০০ ৳)'
                ]),
                'help_text'  => 'মুদ্রার চিহ্নের অবস্থান',
                'sort_order' => 2,
                'is_active'  => true,
            ],
            [
                'key'         => 'decimal_places',
                'value'       => '2',
                'label'       => 'দশমিক স্থান',
                'type'        => 'number',
                'group'       => 'currency',
                'placeholder' => '2',
                'help_text'   => 'কত ঘর দশমিক দেখাবে (০-৪)',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'     => 'thousand_separator',
                'value'   => ',',
                'label'   => 'হাজার সেপারেটর',
                'type'    => 'select',
                'group'   => 'currency',
                'options' => json_encode([
                    ',' => 'কমা (,)',
                    '.' => 'ডট (.)',
                    ' ' => 'স্পেস ( )',
                    "'" => 'অ্যাপোস্ট্রফি (\')'
                ]),
                'help_text'  => 'হাজারের বিভাজক চিহ্ন',
                'sort_order' => 4,
                'is_active'  => true,
            ],

            // =============================================
            // ৬. DATE & TIME SETTINGS
            // =============================================
            [
                'key'     => 'date_format',
                'value'   => 'd-m-Y',
                'label'   => 'তারিখ ফরম্যাট',
                'type'    => 'select',
                'group'   => 'date',
                'options' => json_encode([
                    'd-m-Y' => 'DD-MM-YYYY (২৫-১২-২০২৪)',
                    'm-d-Y' => 'MM-DD-YYYY (১২-২৫-২০২৪)',
                    'Y-m-d' => 'YYYY-MM-DD (২০২৪-১২-২৫)',
                    'd M Y' => 'DD Mon YYYY (২৫ Dec ২০২৪)',
                    'd F Y' => 'DD Month YYYY (২৫ December ২০২৪)'
                ]),
                'help_text'  => 'সাইটে তারিখ দেখানোর ফরম্যাট',
                'sort_order' => 1,
                'is_active'  => true,
            ],
            [
                'key'     => 'timezone',
                'value'   => 'Asia/Dhaka',
                'label'   => 'টাইমজোন',
                'type'    => 'select',
                'group'   => 'date',
                'options' => json_encode([
                    'Asia/Dhaka'       => 'Asia/Dhaka (GMT+6)',
                    'Asia/Calcutta'    => 'Asia/Calcutta (GMT+5:30)',
                    'UTC'              => 'UTC',
                    'America/New_York' => 'America/New York (GMT-5)',
                    'Europe/London'    => 'Europe/London (GMT+0)'
                ]),
                'help_text'  => 'আপনার লোকাল টাইমজোন সিলেক্ট করুন',
                'sort_order' => 2,
                'is_active'  => true,
            ],

            // =============================================
            // ৭. INVOICE SETTINGS
            // =============================================
            [
                'key'         => 'invoice_prefix',
                'value'       => 'INV',
                'label'       => 'ইনভয়েস প্রিফিক্স',
                'type'        => 'text',
                'group'       => 'invoice',
                'placeholder' => 'INV',
                'help_text'   => 'ইনভয়েস নম্বরের শুরুতে যা যোগ হবে',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'invoice_start_number',
                'value'       => '1000',
                'label'       => 'ইনভয়েস শুরু নম্বর',
                'type'        => 'number',
                'group'       => 'invoice',
                'placeholder' => '1000',
                'help_text'   => 'ইনভয়েস নম্বর শুরু হবে এই নম্বর থেকে',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'invoice_footer_text',
                'value'       => 'ধন্যবাদ আমাদের সাথে কেনাকাটা করার জন্য। আপনার প্রতিটি কেনাকাটায় আমরা সেবা দিতে বদ্ধপরিকর।',
                'label'       => 'ইনভয়েস ফুটার টেক্সট',
                'type'        => 'textarea',
                'group'       => 'invoice',
                'placeholder' => 'ইনভয়েসের নিচের লেখা',
                'help_text'   => 'প্রত্যেক ইনভয়েসের নিচে এই টেক্সট দেখাবে',
                'sort_order'  => 3,
                'is_active'   => true,
            ],

            // =============================================
            // ৮. EMAIL SETTINGS
            // =============================================
            [
                'key'         => 'order_confirmation_subject',
                'value'       => 'আপনার অর্ডার কনফার্ম হয়েছে - হেজবুত তওহীদ',
                'label'       => 'অর্ডার কনফার্মেশন ইমেইল সাবজেক্ট',
                'type'        => 'text',
                'group'       => 'email',
                'placeholder' => 'অর্ডার কনফার্মেশন',
                'help_text'   => 'অর্ডার কনফার্মেশনের ইমেইলের সাবজেক্ট',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'order_delivered_subject',
                'value'       => 'আপনার অর্ডার ডেলিভারি হয়েছে - হেজবুত তওহীদ',
                'label'       => 'অর্ডার ডেলিভারি ইমেইল সাবজেক্ট',
                'type'        => 'text',
                'group'       => 'email',
                'placeholder' => 'অর্ডার ডেলিভারি হয়েছে',
                'help_text'   => 'অর্ডার ডেলিভারির ইমেইলের সাবজেক্ট',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'order_cancelled_subject',
                'value'       => 'আপনার অর্ডার বাতিল করা হয়েছে - হেজবুত তওহীদ',
                'label'       => 'অর্ডার ক্যান্সেল ইমেইল সাবজেক্ট',
                'type'        => 'text',
                'group'       => 'email',
                'placeholder' => 'অর্ডার বাতিল করা হয়েছে',
                'help_text'   => 'অর্ডার ক্যান্সেলের ইমেইলের সাবজেক্ট',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'newsletter_subject',
                'value'       => 'আমাদের নিউজলেটারে সাবস্ক্রাইবের জন্য ধন্যবাদ - হেজবুত তওহীদ',
                'label'       => 'নিউজলেটার ইমেইল সাবজেক্ট',
                'type'        => 'text',
                'group'       => 'email',
                'placeholder' => 'নিউজলেটার সাবস্ক্রিপশন',
                'help_text'   => 'নিউজলেটার সাবস্ক্রাইবের ইমেইলের সাবজেক্ট',
                'sort_order'  => 4,
                'is_active'   => true,
            ],

            // =============================================
            // ৯. SHIPPING & DELIVERY SETTINGS
            // =============================================
            [
                'key'         => 'free_shipping_threshold',
                'value'       => '1500',
                'label'       => 'ফ্রি শিপিং থ্রেশহোল্ড',
                'type'        => 'number',
                'group'       => 'shipping',
                'placeholder' => '১৫০০',
                'help_text'   => 'এই পরিমাণ টাকার অর্ডারে ডেলিভারি চার্জ ফ্রি হবে',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'shipping_charge',
                'value'       => '60',
                'label'       => 'ডেলিভারি চার্জ',
                'type'        => 'number',
                'group'       => 'shipping',
                'placeholder' => '৬০',
                'help_text'   => 'প্রতি অর্ডারে ডেলিভারি চার্জ',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'shipping_delivery_time',
                'value'       => '২৪-৪৮ ঘন্টা',
                'label'       => 'ডেলিভারি সময়',
                'type'        => 'text',
                'group'       => 'shipping',
                'placeholder' => '২৪-৪৮ ঘন্টা',
                'help_text'   => 'অর্ডার ডেলিভারির গড় সময়',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'enable_delivery_geofencing',
                'value'       => '0',
                'label'       => 'ডেলিভারি জিও-ফেন্সিং ওটিপি ভেরিফিকেশন',
                'type'        => 'select',
                'group'       => 'shipping',
                'options'     => json_encode([
                    '0' => 'নিষ্ক্রিয় (সহজ ওটিপি ভেরিফিকেশন)',
                    '1' => 'সক্রিয় (২০০ মিটার রেডিয়াস জিপিএস চেক)'
                ]),
                'placeholder' => '',
                'help_text'   => 'এটি সক্রিয় থাকলে রাইডারকে অবশ্যই ওটিপি ভেরিফাই করার জন্য কাস্টমার অ্যাড্রেসের ২০০ মিটারের মধ্যে থাকতে হবে।',
                'sort_order'  => 4,
                'is_active'   => true,
            ],
            [
                'key'         => 'delivery_radius_km',
                'value'       => '50',
                'label'       => 'ডেলিভারি কাভারেজ এলাকা (কিমি)',
                'type'        => 'number',
                'group'       => 'shipping',
                'placeholder' => '৫০',
                'help_text'   => 'কাস্টমারের ঠিকানা থেকে কত কিলোমিটারের মধ্যে ডেলিভারি সম্ভব',
                'sort_order'  => 5,
                'is_active'   => true,
            ],
            [
                'key'         => 'delivery_schedule_enabled',
                'value'       => '1',
                'label'       => 'ডেলিভারি সময় নির্ধারণ সক্রিয়',
                'type'        => 'select',
                'group'       => 'shipping',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'সক্রিয়'
                ]),
                'help_text'   => 'ক্রেতা তার পছন্দমতো ডেলিভারি সময় নির্ধারণ করতে পারবে',
                'sort_order'  => 6,
                'is_active'   => true,
            ],
            [
                'key'         => 'delivery_time_slots',
                'value'       => json_encode([
                    'সকাল ১০-১২',
                    'দুপুর ১২-২',
                    'বিকাল ২-৪',
                    'বিকাল ৪-৬',
                    'সন্ধ্যা ৬-৮'
                ]),
                'label'       => 'ডেলিভারি সময় স্লট',
                'type'        => 'textarea',
                'group'       => 'shipping',
                'placeholder' => '["সকাল ১০-১২", "দুপুর ১২-২"]',
                'help_text'   => 'JSON ফরম্যাটে ডেলিভারি সময় স্লট লিস্ট',
                'sort_order'  => 7,
                'is_active'   => true,
            ],
            [
                'key'         => 'max_order_per_day',
                'value'       => '100',
                'label'       => 'দৈনিক সর্বোচ্চ অর্ডার সংখ্যা',
                'type'        => 'number',
                'group'       => 'shipping',
                'placeholder' => '১০০',
                'help_text'   => 'একদিনে সর্বোচ্চ কত অর্ডার গ্রহণ করা হবে (০ = সীমাহীন)',
                'sort_order'  => 8,
                'is_active'   => true,
            ],

            // =============================================
            // ১০. PAYMENT SETTINGS
            // =============================================
            [
                'key'         => 'payment_methods',
                'value'       => json_encode(['cod', 'bkash', 'nagad', 'rocket', 'card']),
                'label'       => 'পেমেন্ট মেথড সমূহ',
                'type'        => 'textarea',
                'group'       => 'payment',
                'placeholder' => '["cod", "bkash", "nagad", "rocket", "card"]',
                'help_text'   => 'সাপোর্টেড পেমেন্ট মেথড লিস্ট (JSON ফরম্যাটে)',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'cod_enabled',
                'value'       => '1',
                'label'       => 'ক্যাশ অন ডেলিভারি (COD) সক্রিয়',
                'type'        => 'select',
                'group'       => 'payment',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'সক্রিয়'
                ]),
                'help_text'   => 'COD পেমেন্ট মেথড সক্রিয়/নিষ্ক্রিয় করুন',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'bkash_enabled',
                'value'       => '1',
                'label'       => 'বিকাশ পেমেন্ট সক্রিয়',
                'type'        => 'select',
                'group'       => 'payment',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'সক্রিয়'
                ]),
                'help_text'   => 'বিকাশ পেমেন্ট গেটওয়ে সক্রিয়/নিষ্ক্রিয় করুন',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'bkash_merchant_number',
                'value'       => '01712345678',
                'label'       => 'বিকাশ মার্চেন্ট নম্বর',
                'type'        => 'text',
                'group'       => 'payment',
                'placeholder' => '০১৭১২৩৪৫৬৭৮',
                'help_text'   => 'বিকাশ মার্চেন্ট অ্যাকাউন্ট নম্বর',
                'sort_order'  => 4,
                'is_active'   => true,
            ],
            [
                'key'         => 'nagad_enabled',
                'value'       => '1',
                'label'       => 'নগদ পেমেন্ট সক্রিয়',
                'type'        => 'select',
                'group'       => 'payment',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'সক্রিয়'
                ]),
                'help_text'   => 'নগদ পেমেন্ট গেটওয়ে সক্রিয়/নিষ্ক্রিয় করুন',
                'sort_order'  => 5,
                'is_active'   => true,
            ],
            [
                'key'         => 'nagad_merchant_number',
                'value'       => '01712345678',
                'label'       => 'নগদ মার্চেন্ট নম্বর',
                'type'        => 'text',
                'group'       => 'payment',
                'placeholder' => '০১৭১২৩৪৫৬৭৮',
                'help_text'   => 'নগদ মার্চেন্ট অ্যাকাউন্ট নম্বর',
                'sort_order'  => 6,
                'is_active'   => true,
            ],

            // =============================================
            // ১১. MAINTENANCE SETTINGS
            // =============================================
            [
                'key'         => 'maintenance_mode',
                'value'       => '0',
                'label'       => 'মেইনটেন্যান্স মোড',
                'type'        => 'select',
                'group'       => 'maintenance',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'চালু'
                ]),
                'help_text'   => 'সাইট মেইনটেন্যান্সের জন্য বন্ধ রাখুন',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'maintenance_message',
                'value'       => 'আমরা সাইট আপডেট করছি। দয়া করে কিছুক্ষণ পর আবার চেষ্টা করুন।',
                'label'       => 'মেইনটেন্যান্স মেসেজ',
                'type'        => 'textarea',
                'group'       => 'maintenance',
                'placeholder' => 'মেইনটেন্যান্স বার্তা',
                'help_text'   => 'মেইনটেন্যান্স মোড চালু থাকলে এই বার্তা দেখাবে',
                'sort_order'  => 2,
                'is_active'   => true,
            ],

            // =============================================
            // ১২. COOKIE CONSENT SETTINGS
            // =============================================
            [
                'key'         => 'cookie_consent_enabled',
                'value'       => '1',
                'label'       => 'কুকি কনসেন্ট সক্রিয়',
                'type'        => 'select',
                'group'       => 'cookie',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'চালু'
                ]),
                'help_text'   => 'কুকি কনসেন্ট বার সক্রিয়/নিষ্ক্রিয় করুন',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'cookie_consent_message',
                'value'       => 'আমরা আপনার অভিজ্ঞতা উন্নত করতে কুকি ব্যবহার করি। আমাদের সাইট ব্যবহার করে আপনি আমাদের কুকি পলিসিতে সম্মতি দিচ্ছেন।',
                'label'       => 'কুকি কনসেন্ট বার্তা',
                'type'        => 'textarea',
                'group'       => 'cookie',
                'placeholder' => 'কুকি কনসেন্ট বার্তা',
                'help_text'   => 'কুকি কনসেন্ট বারে দেখানোর বার্তা',
                'sort_order'  => 2,
                'is_active'   => true,
            ],

            // =============================================
            // ১৩. CHECKOUT SETTINGS (নতুন যোগ করা)
            // =============================================
            [
                'key'         => 'checkout_guest_enabled',
                'value'       => '1',
                'label'       => 'গেস্ট চেকআউট সক্রিয়',
                'type'        => 'select',
                'group'       => 'checkout',
                'options'     => json_encode([
                    '0' => 'বন্ধ (শুধু রেজিস্টার্ড ইউজার)',
                    '1' => 'সক্রিয় (গেস্ট ইউজার অর্ডার করতে পারবে)'
                ]),
                'help_text'   => 'অ্যাকাউন্ট ছাড়াই ক্রেতারা অর্ডার করতে পারবে কিনা',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'checkout_phone_auto_check',
                'value'       => '1',
                'label'       => 'ফোন নম্বর অটো-চেক সক্রিয়',
                'type'        => 'select',
                'group'       => 'checkout',
                'options'     => json_encode([
                    '0' => 'বন্ধ (ম্যানুয়াল চেক)',
                    '1' => 'সক্রিয় (অটো-চেক ও ঠিকানা লোড)'
                ]),
                'help_text'   => 'মোবাইল নম্বর টাইপ করার সময় স্বয়ংক্রিয়ভাবে কাস্টমার চেক করবে',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'checkout_minimum_order',
                'value'       => '100',
                'label'       => 'ন্যূনতম অর্ডার পরিমাণ',
                'type'        => 'number',
                'group'       => 'checkout',
                'placeholder' => '১০০',
                'help_text'   => 'ন্যূনতম কত টাকার অর্ডার গ্রহণ করা হবে',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'checkout_maximum_order',
                'value'       => '50000',
                'label'       => 'সর্বোচ্চ অর্ডার পরিমাণ',
                'type'        => 'number',
                'group'       => 'checkout',
                'placeholder' => '৫০০০০',
                'help_text'   => 'সর্বোচ্চ কত টাকার অর্ডার গ্রহণ করা হবে',
                'sort_order'  => 4,
                'is_active'   => true,
            ],
            [
                'key'         => 'checkout_terms_required',
                'value'       => '1',
                'label'       => 'টার্মস এন্ড কন্ডিশন চেকবক্স প্রয়োজন',
                'type'        => 'select',
                'group'       => 'checkout',
                'options'     => json_encode([
                    '0' => 'প্রয়োজন নেই',
                    '1' => 'প্রয়োজন (সক্রিয়)'
                ]),
                'help_text'   => 'অর্ডার কনফার্মের আগে টার্মস চেকবক্সে টিক দিতে হবে কিনা',
                'sort_order'  => 5,
                'is_active'   => true,
            ],
            [
                'key'         => 'checkout_auto_restore_data',
                'value'       => '1',
                'label'       => 'লোকাল স্টোরেজ অটো-রিস্টোর',
                'type'        => 'select',
                'group'       => 'checkout',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'সক্রিয় (পেজ রিফ্রেশে ডাটা রিস্টোর)'
                ]),
                'help_text'   => 'পেজ রিফ্রেশ বা রি-এন্টার করলে পূর্বের ডাটা অটো-লোড হবে',
                'sort_order'  => 6,
                'is_active'   => true,
            ],

            // =============================================
            // ১৪. OTP SETTINGS (নতুন যোগ করা)
            // =============================================
            [
                'key'         => 'otp_enabled',
                'value'       => '1',
                'label'       => 'OTP ভেরিফিকেশন সক্রিয়',
                'type'        => 'select',
                'group'       => 'otp',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'সক্রিয়'
                ]),
                'help_text'   => 'অর্ডার কনফার্মেশনের সময় OTP ভেরিফিকেশন প্রয়োজন',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'otp_expiry_minutes',
                'value'       => '5',
                'label'       => 'OTP মেয়াদ (মিনিট)',
                'type'        => 'number',
                'group'       => 'otp',
                'placeholder' => '৫',
                'help_text'   => 'OTP কত মিনিট পর্যন্ত বৈধ থাকবে',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'otp_attempts',
                'value'       => '3',
                'label'       => 'OTP চেষ্টার সীমা',
                'type'        => 'number',
                'group'       => 'otp',
                'placeholder' => '৩',
                'help_text'   => 'কতবার ভুল OTP দিলে ব্লক হবে',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'otp_block_minutes',
                'value'       => '30',
                'label'       => 'OTP ব্লক সময় (মিনিট)',
                'type'        => 'number',
                'group'       => 'otp',
                'placeholder' => '৩০',
                'help_text'   => 'সীমাবদ্ধ OTP চেষ্টার পর কত মিনিট ব্লক থাকবে',
                'sort_order'  => 4,
                'is_active'   => true,
            ],
            [
                'key'         => 'otp_gateway',
                'value'       => 'sms',
                'label'       => 'OTP গেটওয়ে',
                'type'        => 'select',
                'group'       => 'otp',
                'options'     => json_encode([
                    'sms' => 'SMS',
                    'whatsapp' => 'WhatsApp',
                    'both' => 'SMS + WhatsApp'
                ]),
                'help_text'   => 'OTP পাঠানোর মাধ্যম নির্বাচন করুন',
                'sort_order'  => 5,
                'is_active'   => true,
            ],

            // =============================================
            // ১৫. SECURITY & RECAPTCHA SETTINGS (সিকিউরিটি ও রিক্যাপচা সেটিংস)
            // =============================================
            [
                'key'         => 'enable_recaptcha',
                'value'       => '0',
                'label'       => 'Google reCAPTCHA সক্রিয়',
                'type'        => 'select',
                'group'       => 'security',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'চালু'
                ]),
                'help_text'   => 'লগইন এবং চেকআউট পেজে রিক্যাপচা সিকিউরিটি চালু করতে',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'recaptcha_site_key',
                'value'       => null,
                'label'       => 'reCAPTCHA Site Key',
                'type'        => 'text',
                'group'       => 'security',
                'placeholder' => 'আপনার গুগল রিক্যাপচা সাইট কী লিখুন',
                'help_text'   => 'Google reCAPTCHA v2 / v3 সাইট কী',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'recaptcha_secret_key',
                'value'       => null,
                'label'       => 'reCAPTCHA Secret Key',
                'type'        => 'text',
                'group'       => 'security',
                'placeholder' => 'আপনার গুগল রিক্যাপচা সিক্রেট কী লিখুন',
                'help_text'   => 'Google reCAPTCHA v2 / v3 সিক্রেট কী',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'session_timeout',
                'value'       => '120',
                'label'       => 'সেশন টাইমআউট (মিনিট)',
                'type'        => 'number',
                'group'       => 'security',
                'placeholder' => '১২০',
                'help_text'   => 'কত মিনিট ইন-অ্যাক্টিভ থাকলে লগআউট হবে',
                'sort_order'  => 4,
                'is_active'   => true,
            ],
            [
                'key'         => 'enable_brute_force_protection',
                'value'       => '1',
                'label'       => 'লগইন ব্রুট-ফোর্স প্রটেকশন',
                'type'        => 'select',
                'group'       => 'security',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'চালু'
                ]),
                'help_text'   => 'ভুল পাসওয়ার্ড দিয়ে ক্রমাগত চেষ্টা করলে অ্যাকাউন্ট লক করা হবে',
                'sort_order'  => 5,
                'is_active'   => true,
            ],
            [
                'key'         => 'max_login_attempts',
                'value'       => '5',
                'label'       => 'সর্বোচ্চ লগইন চেষ্টার সীমা',
                'type'        => 'number',
                'group'       => 'security',
                'placeholder' => '৫',
                'help_text'   => 'কতবার ভুল লগইন চেষ্টা করলে অ্যাকাউন্ট লক হবে',
                'sort_order'  => 6,
                'is_active'   => true,
            ],
            [
                'key'         => 'lockout_time_minutes',
                'value'       => '15',
                'label'       => 'লকআউট সময়কাল (মিনিট)',
                'type'        => 'number',
                'group'       => 'security',
                'placeholder' => '১৫',
                'help_text'   => 'অ্যাকাউন্ট লক হওয়ার পর কত মিনিট অপেক্ষা করতে হবে',
                'sort_order'  => 7,
                'is_active'   => true,
            ],

            // =============================================
            // ১৬. SHOP & INVENTORY SETTINGS (শপ ও ইনভেন্টরি সেটিংস)
            // =============================================
            [
                'key'         => 'enable_inventory_tracking',
                'value'       => '1',
                'label'       => 'ইনভেন্টরি ট্র্যাকিং সক্রিয়',
                'type'        => 'select',
                'group'       => 'inventory',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'চালু'
                ]),
                'help_text'   => 'প্রোডাক্টের স্টক ম্যানেজমেন্ট ও ট্র্যাকিং চালু করতে',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'low_stock_notification',
                'value'       => '1',
                'label'       => 'লো-স্টক নোটিফিকেশন সক্রিয়',
                'type'        => 'select',
                'group'       => 'inventory',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'চালু'
                ]),
                'help_text'   => 'কোনো প্রোডাক্টের স্টক কমে গেলে এডমিনকে নোটিফাই করা হবে কিনা',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'low_stock_threshold',
                'value'       => '5',
                'label'       => 'লো-স্টক নোটিফিকেশন থ্রেশহোল্ড',
                'type'        => 'number',
                'group'       => 'inventory',
                'placeholder' => '৫',
                'help_text'   => 'স্টক এই সংখ্যা বা তার নিচে নামলে নোটিফাই করা হবে',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'allow_out_of_stock_orders',
                'value'       => '0',
                'label'       => 'আউট-অফ-স্টক প্রোডাক্ট অর্ডার',
                'type'        => 'select',
                'group'       => 'inventory',
                'options'     => json_encode([
                    '0' => 'বন্ধ (অর্ডার করা যাবে না)',
                    '1' => 'চালু (অর্ডার করা যাবে / ব্যাকঅর্ডার)'
                ]),
                'help_text'   => 'স্টক না থাকলেও ক্রেতারা অর্ডার করতে পারবে কিনা',
                'sort_order'  => 4,
                'is_active'   => true,
            ],

            // =============================================
            // ১৭. TAX & VAT SETTINGS (ট্যাক্স ও ভ্যাট সেটিংস)
            // =============================================
            [
                'key'         => 'enable_tax_vat',
                'value'       => '0',
                'label'       => 'ট্যাক্স এবং ভ্যাট সক্রিয়',
                'type'        => 'select',
                'group'       => 'tax_vat',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'চালু'
                ]),
                'help_text'   => 'অর্ডারের উপর ট্যাক্স/ভ্যাট হিসাব সক্রিয় করতে',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'vat_percentage',
                'value'       => '5',
                'label'       => 'ভ্যাট শতকরা হার (%)',
                'type'        => 'number',
                'group'       => 'tax_vat',
                'placeholder' => '৫',
                'help_text'   => 'ভ্যাটের ডিফল্ট হার (পার্সেন্টেজ)',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'tax_number',
                'value'       => null,
                'label'       => 'ট্যাক্স/ভ্যাট রেজিস্ট্রেশন নম্বর (BIN)',
                'type'        => 'text',
                'group'       => 'tax_vat',
                'placeholder' => 'আপনার ভ্যাট রেজিস্ট্রেশন নম্বর',
                'help_text'   => 'ইনভয়েসে প্রদর্শন করার জন্য ভ্যাট/ট্যাক্স রেজিস্ট্রেশন নম্বর',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'prices_include_tax',
                'value'       => '1',
                'label'       => 'প্রোডাক্টের মূল্যে ট্যাক্স অন্তর্ভুক্ত',
                'type'        => 'select',
                'group'       => 'tax_vat',
                'options'     => json_encode([
                    '0' => 'না (চেকআউট সময়ে আলাদা যোগ হবে)',
                    '1' => 'হ্যাঁ (প্রোডাক্ট মূল্যের মধ্যেই অন্তর্ভুক্ত)'
                ]),
                'help_text'   => 'প্রদর্শিত প্রোডাক্টের মূল্যের মধ্যে ভ্যাট অন্তর্ভুক্ত আছে কিনা',
                'sort_order'  => 4,
                'is_active'   => true,
            ],

            // =============================================
            // ১৮. ABOUT PAGE SETTINGS (আমাদের সম্পর্কে পেজ সেটিংস)
            // =============================================
            [
                'key'         => 'about_hero_badge',
                'value'       => 'আমাদের সম্পর্কে',
                'label'       => 'হিরো সেকশন ব্যাজ',
                'type'        => 'text',
                'group'       => 'about',
                'placeholder' => 'যেমন: আমাদের সম্পর্কে',
                'help_text'   => 'এবাউট পেজের হিরো সেকশনের ছোট ব্যাজ টেক্সট',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_hero_title',
                'value'       => 'বিশ্বাসের <span>হেজবুত তওহীদ</span>',
                'label'       => 'হিরো সেকশন টাইটেল',
                'type'        => 'text',
                'group'       => 'about',
                'placeholder' => 'বিশ্বাসের <span>হেজবুত তওহীদ</span>',
                'help_text'   => 'এবাউট পেজের হিরো সেকশনের শিরোনাম (HTML কোড ব্যবহার করা যাবে)',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_hero_description',
                'value'       => 'দেশের সবচেয়ে বিশ্বস্ত অনলাইন সুপারশপ। আমরা চাই প্রতিটি ঘরে পৌঁছে দিতে তাজা ও মানসম্পন্ন পণ্য।',
                'label'       => 'হিরো সেকশন বিবরণ',
                'type'        => 'textarea',
                'group'       => 'about',
                'placeholder' => 'হিরো সেকশনের বিস্তারিত বিবরণ লিখুন',
                'help_text'   => 'এবাউট পেজের হিরো সেকশনের ছোট বিবরণ',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_hero_features',
                'value'       => '১০০% তাজা পণ্য,দ্রুত ডেলিভারি,সেরা দাম',
                'label'       => 'হিরো সেকশন বৈশিষ্ট্যসমূহ',
                'type'        => 'text',
                'group'       => 'about',
                'placeholder' => 'তাজা পণ্য,দ্রুত ডেলিভারি,সেরা দাম',
                'help_text'   => 'কমা দিয়ে আলাদা করে বৈশিষ্ট্যগুলো লিখুন',
                'sort_order'  => 4,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_mission_mission_title',
                'value'       => 'আমাদের মিশন',
                'label'       => 'মিশন টাইটেল',
                'type'        => 'text',
                'group'       => 'about',
                'placeholder' => 'আমাদের মিশন',
                'help_text'   => 'মিশন বক্সের শিরোনাম',
                'sort_order'  => 5,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_mission_mission_desc',
                'value'       => 'বাংলাদেশের প্রতিটি ঘরে পৌঁছে দেওয়া তাজা ও মানসম্পন্ন পণ্য। আমরা চাই প্রতিটি ক্রেতা তার কেনাকাটায় সন্তুষ্ট থাকুক এবং আমাদের সেবায় বিশ্বাস রাখুক।',
                'label'       => 'মিশন বিবরণ',
                'type'        => 'textarea',
                'group'       => 'about',
                'placeholder' => 'মিশন বিবরণ লিখুন',
                'help_text'   => 'আমাদের মিশনের বিস্তারিত বিবরণ',
                'sort_order'  => 6,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_mission_features',
                'value'       => 'তাজা পণ্য,মান নিশ্চিত,সাশ্রয়ী মূল্য',
                'label'       => 'মিশন বৈশিষ্ট্যসমূহ',
                'type'        => 'text',
                'group'       => 'about',
                'placeholder' => 'তাজা পণ্য,মান নিশ্চিত,সাশ্রয়ী মূল্য',
                'help_text'   => 'কমা দিয়ে আলাদা করে মিশনের বৈশিষ্ট্যগুলো লিখুন',
                'sort_order'  => 7,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_vision_title',
                'value'       => 'আমাদের ভিশন',
                'label'       => 'ভিশন টাইটেল',
                'type'        => 'text',
                'group'       => 'about',
                'placeholder' => 'আমাদের ভিশন',
                'help_text'   => 'ভিশন বক্সের শিরোনাম',
                'sort_order'  => 8,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_vision_desc',
                'value'       => 'বাংলাদেশের সবচেয়ে বিশ্বস্ত ও জনপ্রিয় অনলাইন সুপারশপ হিসেবে নিজেদের প্রতিষ্ঠা করা। প্রযুক্তি ও সেবার সমন্বয়ে ক্রেতার জীবনকে সহজ করা।',
                'label'       => 'ভিশন বিবরণ',
                'type'        => 'textarea',
                'group'       => 'about',
                'placeholder' => 'ভিশন বিবরণ লিখুন',
                'help_text'   => 'আমাদের ভিশনের বিস্তারিত বিবরণ',
                'sort_order'  => 9,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_vision_features',
                'value'       => 'প্রযুক্তি নির্ভর,বিশ্বস্ত সেবা,গ্রাহক কেন্দ্রিক',
                'label'       => 'ভিশন বৈশিষ্ট্যসমূহ',
                'type'        => 'text',
                'group'       => 'about',
                'placeholder' => 'প্রযুক্তি নির্ভর,বিশ্বস্ত সেবা,গ্রাহক কেন্দ্রিক',
                'help_text'   => 'কমা দিয়ে আলাদা করে ভিশনের বৈশিষ্ট্যগুলো লিখুন',
                'sort_order'  => 10,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_values_items',
                'value'       => json_encode([
                    ['icon' => 'fa-shield-alt', 'title' => 'সবুজ ও সতেজ', 'description' => 'আমরা সরাসরি কৃষকদের কাছ থেকে তাজা সবজি ও ফলমূল সংগ্রহ করি।', 'color' => '#00A65A'],
                    ['icon' => 'fa-clock', 'title' => 'নিশ্চিত সেবা', 'description' => 'সময়মতো এবং দ্রুত ডেলিভারি নিশ্চিত করতে আমরা প্রতিশ্রুতিবদ্ধ।', 'color' => '#3b82f6'],
                    ['icon' => 'fa-hand-holding-heart', 'title' => 'গ্রাহক সন্তুষ্টি', 'description' => 'গ্রাহকের মতামত ও সন্তুষ্টিই আমাদের ব্যবসার চালিকাশক্তি।', 'color' => '#f59e0b'],
                    ['icon' => 'fa-leaf', 'title' => 'পরিবেশবান্ধব', 'description' => 'পরিবেশ রক্ষা করতে আমরা জৈব উপাদান ও রিইউজেবল প্যাকেট ব্যবহার করি।', 'color' => '#8b5cf6'],
                    ['icon' => 'fa-rocket', 'title' => 'সহজ অভিজ্ঞতা', 'description' => 'আমাদের ইউজার-ফ্রেন্ডলি অ্যাপ ও ওয়েবসাইট কেনাকাটা করে তোলে পানির মতো সহজ।', 'color' => '#ef4444'],
                    ['icon' => 'fa-handshake', 'title' => 'স্বচ্ছ মূল্য', 'description' => 'কোনো লুকানো চার্জ ছাড়াই ঢাকার সবথেকে সেরা দামে আমরা পণ্য সরবরাহ করি।', 'color' => '#06b6d4']
                ], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT),
                'label'       => 'আমাদের মূল্যবোধসমূহ (JSON)',
                'type'        => 'json',
                'group'       => 'about',
                'placeholder' => '[{"icon": "fa-shield-alt", "title": "সবুজ ও সতেজ", "description": "...", "color": "#00A65A"}]',
                'help_text'   => 'মূল্যবোধ কার্ডের তালিকা (JSON ফরম্যাটে)',
                'sort_order'  => 11,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_why_items',
                'value'       => json_encode([
                    ['icon' => 'fa-truck', 'title' => 'তাত্ক্ষণিক ডেলিভারি', 'description' => 'অর্ডারের পর নির্দিষ্ট সময়সীমার মধ্যে পণ্য আপনার দরজায়', 'color' => '#017e3d'],
                    ['icon' => 'fa-shield-alt', 'title' => '১০০% তাজা পণ্য', 'description' => 'প্রতিটি ফলমূল ও সবজির ১০০% সতেজতার নিশ্চয়তা', 'color' => '#2563eb'],
                    ['icon' => 'fa-undo-alt', 'title' => 'সহজ রিটার্ন পলিসি', 'description' => 'পণ্য পছন্দ না হলে তাৎক্ষণিক রিটার্ন ও রিফান্ড সুবিধা', 'color' => '#f59e0b'],
                    ['icon' => 'fa-headset', 'title' => 'সার্বক্ষণিক কাস্টমার কেয়ার', 'description' => 'যেকোনো সমস্যায় আমাদের সাপোর্ট টিম আপনার পাশেই আছে', 'color' => '#8b5cf6'],
                    ['icon' => 'fa-wallet', 'title' => 'ক্যাশ অন ডেলিভারি', 'description' => 'আগে পণ্য বুঝে নিন, তারপর পেমেন্ট করুন নিরাপদে', 'color' => '#ef4444'],
                    ['icon' => 'fa-award', 'title' => 'সেরা ব্র্যান্ড গ্যারান্টি', 'description' => 'বাজারের বিশ্বস্ত ও সেরা ব্র্যান্ডের পণ্যসমূহের সমাহার', 'color' => '#06b6d4']
                ], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT),
                'label'       => 'কেন আমাদের বেছে নেবেন (JSON)',
                'type'        => 'json',
                'group'       => 'about',
                'placeholder' => '[{"icon": "fa-truck", "title": "তাত্ক্ষণিক ডেলিভারি", "description": "...", "color": "#017e3d"}]',
                'help_text'   => 'কেন বেছে নেবেন কার্ডের তালিকা (JSON ফরম্যাটে)',
                'sort_order'  => 12,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_cta_title',
                'value'       => 'আজই শুরু করুন আপনার কেনাকাটা',
                'label'       => 'CTA সেকশন টাইটেল',
                'type'        => 'text',
                'group'       => 'about',
                'placeholder' => 'আজই শুরু করুন আপনার কেনাকাটা',
                'help_text'   => 'CTA (কল টু অ্যাকশন) সেকশনের শিরোনাম',
                'sort_order'  => 13,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_cta_desc',
                'value'       => 'তাজা পণ্য, সেরা দাম এবং দ্রুত ডেলিভারি পেতে এখনই অর্ডার করুন',
                'label'       => 'CTA সেকশন বিবরণ',
                'type'        => 'textarea',
                'group'       => 'about',
                'placeholder' => 'CTA সেকশনের বিবরণ লিখুন',
                'help_text'   => 'CTA (কল টু অ্যাকশন) সেকশনের বিবরণ',
                'sort_order'  => 14,
                'is_active'   => true,
            ],
        ];

        // Insert settings
        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }

        $this->command->info('✅ Settings seeded successfully!');
        $this->command->info('📊 Total ' . count($settings) . ' settings inserted.');
    }
}
