<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            // General Settings
            [
                'key'         => 'company_name',
                'value'       => 'হেযবুত তওহীদ',
                'label'       => 'কোম্পানির নাম',
                'type'        => 'text',
                'group'       => 'general',
                'placeholder' => 'আপনার কোম্পানির নাম লিখুন',
                'help_text'   => 'ওয়েবসাইটের সর্বত্র এই নাম দেখাবে',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_tagline',
                'value'       => 'একটি অরাজনৈতিক ধর্মীয় সংস্কারমূলক আন্দোলন',
                'label'       => 'কোম্পানির ট্যাগলাইন',
                'type'        => 'text',
                'group'       => 'general',
                'placeholder' => 'যেমন: মানবতার কল্যাণে...',
                'help_text'   => 'কোম্পানির স্লোগান বা ট্যাগলাইন',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_description',
                'value'       => 'হেযবুত তওহীদ একটি অরাজনৈতিক ধর্মভিত্তিক আন্দোলন। ১৯৯৫ সালে টাঙ্গাইলের করটিয়ায় আন্দোলনটি প্রতিষ্ঠিত হয়। হেযবুত তওহীদের প্রতিষ্ঠাতা এমামুযযামান জনাব মোহাম্মদ বায়াজীদ খান পন্নী। ২০১২ সালের ১৬ জানুয়ারি মহামান্য এমামুযযামানের ইন্তেকালের পর হেযবুত তওহীদের এমামের দায়িত্ব গ্রহণ করেন জনাব হোসাইন মোহাম্মদ সেলিম।',
                'label'       => 'কোম্পানির বিবরণ',
                'type'        => 'textarea',
                'group'       => 'general',
                'placeholder' => 'কোম্পানি সম্পর্কে সংক্ষিপ্ত বিবরণ',
                'help_text'   => 'হোমপেজ ও ফুটারে দেখাবে',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_address',
                'value'       => 'বাড়ী # ০৩, রোড # ২০/এ, সেক্টর # ১৪, উত্তরা আজমপুর, ঢাকা-১২৩০',
                'label'       => 'কোম্পানির ঠিকানা',
                'type'        => 'textarea',
                'group'       => 'general',
                'placeholder' => 'পূর্ণ ঠিকানা লিখুন',
                'help_text'   => 'আপনার কোম্পানির ভৌত ঠিকানা',
                'sort_order'  => 4,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_phone',
                'value'       => '0171-1005 025, 0167-0174 643',
                'label'       => 'ফোন নম্বর',
                'type'        => 'text',
                'group'       => 'general',
                'placeholder' => '+৮৮০ ১XXX-XXXXXXX',
                'help_text'   => 'প্রধান যোগাযোগের নম্বর',
                'sort_order'  => 5,
                'is_active'   => true,
            ],
            [
                'key'         => 'company_email',
                'value'       => 'askhezbuttawheed@gmail.com',
                'label'       => 'ইমেইল ঠিকানা',
                'type'        => 'email',
                'group'       => 'general',
                'placeholder' => 'info@yourcompany.com',
                'help_text'   => 'প্রধান ইমেইল ঠিকানা',
                'sort_order'  => 6,
                'is_active'   => true,
            ],
            [
                'key'         => 'working_hours',
                'value'       => 'সকাল ৯:০০ - বিকাল ৫:০০ (শনিবার - বৃহস্পতিবার)',
                'label'       => 'কাজের সময়',
                'type'        => 'text',
                'group'       => 'general',
                'placeholder' => 'সকাল ৯টা - বিকাল ৫টা',
                'help_text'   => 'কোম্পানির কার্যক্রমের সময়',
                'sort_order'  => 7,
                'is_active'   => true,
            ],
            [
                'key'         => 'primary_font',
                'value'       => 'SolaimanLipi',
                'label'       => 'মূল ফন্ট (Primary Font)',
                'type'        => 'select',
                'group'       => 'general',
                'options'     => json_encode([
                    'SolaimanLipi'     => 'SolaimanLipi (প্রথোম আলো স্টাইল)',
                    'Baloo Da 2'       => 'Baloo Da 2 (গোলাকার ফন্ট)',
                    'Hind Siliguri'    => 'Hind Siliguri (স্ট্যান্ডার্ড ফন্ট)',
                    'Li Ador Noirrit'  => 'Li Ador Noirrit (চারকোনা বোল্ড স্লোগান ফন্ট)'
                ], JSON_UNESCAPED_UNICODE),
                'help_text'   => 'ওয়েবসাইটের মূল ফন্ট',
                'sort_order'  => 8,
                'is_active'   => true,
            ],
            [
                'key'         => 'secondary_font',
                'value'       => 'Baloo Da 2',
                'label'       => 'সহায়ক ফন্ট (Secondary Font)',
                'type'        => 'select',
                'group'       => 'general',
                'options'     => json_encode([
                    'Baloo Da 2'       => 'Baloo Da 2 (গোলাকার ফন্ট)',
                    'SolaimanLipi'     => 'SolaimanLipi (প্রথোম আলো স্টাইল)',
                    'Hind Siliguri'    => 'Hind Siliguri (স্ট্যান্ডার্ড ফন্ট)',
                    'Li Ador Noirrit'  => 'Li Ador Noirrit (চারকোনা বোল্ড স্লোগান ফন্ট)'
                ], JSON_UNESCAPED_UNICODE),
                'help_text'   => 'ওয়েবসাইটের দ্বিতীয় বা বিকল্প ফন্ট',
                'sort_order'  => 9,
                'is_active'   => true,
            ],

            // Logo Settings
            [
                'key'         => 'company_logo',
                'value'       => null,
                'label'       => 'কোম্পানির লোগো',
                'type'        => 'image',
                'group'       => 'logo',
                'placeholder' => 'লোগো আপলোড করুন',
                'help_text'   => 'প্রস্তাবিত সাইজ: 200x60px। JPG, PNG, WEBP (সর্বোচ্চ 2MB)',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'favicon',
                'value'       => null,
                'label'       => 'ফেভিকন',
                'type'        => 'image',
                'group'       => 'logo',
                'placeholder' => 'ফেভিকন আপলোড করুন',
                'help_text'   => 'প্রস্তাবিত সাইজ: 32x32px। ICO, PNG (সর্বোচ্চ 1MB)',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'footer_logo',
                'value'       => null,
                'label'       => 'ফুটারে লোগো',
                'type'        => 'image',
                'group'       => 'logo',
                'placeholder' => 'ফুটারে ব্যবহারের লোগো আপলোড করুন',
                'help_text'   => 'ফুটারে ডার্ক ব্যাকগ্রাউন্ডের জন্য উপযুক্ত লোগো (PNG/WEBP)',
                'sort_order'  => 3,
                'is_active'   => true,
            ],

            // Social Settings
            [
                'key'         => 'facebook_url',
                'value'       => 'https://www.facebook.com/emamht',
                'label'       => 'ফেসবুক',
                'type'        => 'url',
                'group'       => 'social',
                'placeholder' => 'https://facebook.com/your-page',
                'help_text'   => 'আপনার ফেসবুক পেইজের লিংক',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'twitter_url',
                'value'       => 'https://twitter.com/hezbuttawheed',
                'label'       => 'টুইটার (X)',
                'type'        => 'url',
                'group'       => 'social',
                'placeholder' => 'https://twitter.com/your-handle',
                'help_text'   => 'আপনার টুইটার প্রোফাইলের লিংক',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'instagram_url',
                'value'       => 'https://instagram.com/hezbuttawheed',
                'label'       => 'ইনস্টাগ্রাম',
                'type'        => 'url',
                'group'       => 'social',
                'placeholder' => 'https://instagram.com/your-profile',
                'help_text'   => 'আপনার ইনস্টাগ্রাম প্রোফাইলের লিংক',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'linkedin_url',
                'value'       => 'https://linkedin.com/company/hezbuttawheed',
                'label'       => 'লিংকডইন',
                'type'        => 'url',
                'group'       => 'social',
                'placeholder' => 'https://linkedin.com/company/your-company',
                'help_text'   => 'আপনার লিংকডইন কোম্পানি পেইজের লিংক',
                'sort_order'  => 4,
                'is_active'   => true,
            ],
            [
                'key'         => 'youtube_url',
                'value'       => 'https://www.youtube.com/channel/UCSCJ8zB-CPD0H5P3R67HzCw',
                'label'       => 'ইউটিউব',
                'type'        => 'url',
                'group'       => 'social',
                'placeholder' => 'https://youtube.com/@your-channel',
                'help_text'   => 'আপনার ইউটিউব চ্যানেলের লিংক',
                'sort_order'  => 5,
                'is_active'   => true,
            ],

            // SEO Settings
            [
                'key'         => 'site_name',
                'value'       => 'হেযবুত তওহীদ',
                'label'       => 'সাইটের নাম',
                'type'        => 'text',
                'group'       => 'seo',
                'placeholder' => 'আপনার সাইটের নাম',
                'help_text'   => 'সার্চ ইঞ্জিনে এই নাম দেখাবে',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'site_title',
                'value'       => 'হেযবুত তওহীদ - একটি অরাজনৈতিক ধর্মীয় সংস্কারমূলক আন্দোলন',
                'label'       => 'সাইট টাইটেল',
                'type'        => 'text',
                'group'       => 'seo',
                'placeholder' => 'সাইটের টাইটেল',
                'help_text'   => 'SEO-এর জন্য গুরুত্বপূর্ণ',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'meta_description',
                'value'       => 'হেযবুত তওহীদ একটি অরাজনৈতিক ধর্মভিত্তিক আন্দোলন। সত্য প্রকাশ এবং চরমপন্থা ও সাম্প্রদায়িকতার বিরুদ্ধে মানুষকে সচেতন করাই আমাদের লক্ষ্য।',
                'label'       => 'মেটা বিবরণ',
                'type'        => 'textarea',
                'group'       => 'seo',
                'placeholder' => 'মেটা ডেসক্রিপশন',
                'help_text'   => 'সার্চ ইঞ্জিনের ফলাফলে সাইটের বিবরণ হিসেবে দেখাবে',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'meta_keywords',
                'value'       => 'হেযবুত তওহীদ, ইসলাম, শান্তি, মানবতার কল্যাণ, অপপ্রচার, জঙ্গিবাদ বিরোধী',
                'label'       => 'মেটা কিওয়ার্ডস',
                'type'        => 'text',
                'group'       => 'seo',
                'placeholder' => 'কীওয়ার্ডগুলো কমা দিয়ে লিখুন',
                'help_text'   => 'SEO কিওয়ার্ডস (কমা দ্বারা আলাদা করা)',
                'sort_order'  => 4,
                'is_active'   => true,
            ],

            // Date Format Settings
            [
                'key'     => 'date_format',
                'value'   => 'd-m-Y',
                'label'   => 'তারিখ ফরম্যাট',
                'type'    => 'select',
                'group'   => 'date',
                'options' => json_encode([
                    'd-m-Y' => 'DD-MM-YYYY (২৫-১২-২০২৪)',
                    'm-d-Y' => 'MM-DD-YYYY (১২-২৫-২০২৪)',
                    'Y-m-d' => 'YYYY-MM-DD (২০২৪-১২-২৫)'
                ]),
                'help_text'  => 'সাইটে তারিখ দেখানোর ফরম্যাট',
                'sort_order' => 1,
                'is_active'  => true,
            ],
            [
                'key'     => 'timezone',
                'value'   => 'Asia/Dhaka',
                'label'   => 'টাইমজোন',
                'type'    => 'select',
                'group'   => 'date',
                'options' => json_encode([
                    'Asia/Dhaka'       => 'Asia/Dhaka (GMT+6)',
                    'UTC'              => 'UTC'
                ]),
                'help_text'  => 'আপনার লোকাল টাইমজোন সিলেক্ট করুন',
                'sort_order' => 2,
                'is_active'  => true,
            ],

            // Email Notifications
            [
                'key'         => 'mail_from_name',
                'value'       => 'হেযবুত তওহীদ',
                'label'       => 'ইমেইল প্রেরকের নাম',
                'type'        => 'text',
                'group'       => 'email',
                'placeholder' => 'হেজবুত তওহীদ',
                'help_text'   => 'প্রেরিত ইমেইলের "From" নাম',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'mail_from_email',
                'value'       => 'noreply@hezbuttawheed.org',
                'label'       => 'ইমেইল প্রেরকের ঠিকানা',
                'type'        => 'email',
                'group'       => 'email',
                'placeholder' => 'noreply@yourdomain.com',
                'help_text'   => 'প্রেরিত ইমেইলের "From" ইমেইল ঠিকানা',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'newsletter_subject',
                'value'       => 'আমাদের নিউজলেটারে যুক্ত হওয়ার জন্য ধন্যবাদ - হেযবুত তওহীদ',
                'label'       => 'নিউজলেটার সাবজেক্ট',
                'type'        => 'text',
                'group'       => 'email',
                'placeholder' => 'নিউজলেটার সাবস্ক্রিপশন',
                'help_text'   => 'নিউজলেটার সাবস্ক্রাইব করার ইমেইলের সাবজেক্ট',
                'sort_order'  => 3,
                'is_active'   => true,
            ],

            // Security Settings
            [
                'key'         => 'enable_recaptcha',
                'value'       => '0',
                'label'       => 'Google reCAPTCHA সক্রিয়',
                'type'        => 'select',
                'group'       => 'security',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'চালু'
                ]),
                'help_text'   => 'লগইন পেজে রিক্যাপচা সিকিউরিটি চালু করতে',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'recaptcha_site_key',
                'value'       => null,
                'label'       => 'reCAPTCHA Site Key',
                'type'        => 'text',
                'group'       => 'security',
                'placeholder' => 'গুগল রিক্যাপচা সাইট কী লিখুন',
                'help_text'   => 'Google reCAPTCHA v2 / v3 সাইট কী',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'recaptcha_secret_key',
                'value'       => null,
                'label'       => 'reCAPTCHA Secret Key',
                'type'        => 'text',
                'group'       => 'security',
                'placeholder' => 'গুগল রিক্যাপচা সিক্রেট কী লিখুন',
                'help_text'   => 'Google reCAPTCHA v2 / v3 সিক্রেট কী',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'session_timeout',
                'value'       => '120',
                'label'       => 'সেশন টাইমআউট (মিনিট)',
                'type'        => 'number',
                'group'       => 'security',
                'placeholder' => '১২০',
                'help_text'   => 'কত মিনিট ইন-অ্যাক্টিভ থাকলে লগআউট হবে',
                'sort_order'  => 4,
                'is_active'   => true,
            ],
            [
                'key'         => 'enable_brute_force_protection',
                'value'       => '1',
                'label'       => 'লগইন ব্রুট-ফোর্স প্রটেকশন',
                'type'        => 'select',
                'group'       => 'security',
                'options'     => json_encode([
                    '0' => 'বন্ধ',
                    '1' => 'চালু'
                ]),
                'help_text'   => 'ভুল পাসওয়ার্ড দিয়ে ক্রমাগত চেষ্টা করলে অ্যাকাউন্ট লক করা হবে',
                'sort_order'  => 5,
                'is_active'   => true,
            ],
            [
                'key'         => 'max_login_attempts',
                'value'       => '5',
                'label'       => 'সর্বোচ্চ লগইন চেষ্টার সীমা',
                'type'        => 'number',
                'group'       => 'security',
                'placeholder' => '৫',
                'help_text'   => 'কতবার ভুল লগইন চেষ্টা করলে অ্যাকাউন্ট লক হবে',
                'sort_order'  => 6,
                'is_active'   => true,
            ],

            // About Page Settings
            [
                'key'         => 'about_hero_badge',
                'value'       => 'আমাদের সম্পর্কে',
                'label'       => 'হিরো সেকশন ব্যাজ',
                'type'        => 'text',
                'group'       => 'about',
                'placeholder' => 'যেমন: আমাদের সম্পর্কে',
                'help_text'   => 'এবাউট পেজের হিরো সেকশনের ছোট ব্যাজ টেক্সট',
                'sort_order'  => 1,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_hero_title',
                'value'       => 'মানবতার কল্যাণে হেযবুত তওহীদের ভূমিকা',
                'label'       => 'হিরো সেকশন টাইটেল',
                'type'        => 'text',
                'group'       => 'about',
                'placeholder' => 'মানবতার কল্যাণে...',
                'help_text'   => 'এবাউট পেজের হিরো সেকশনের শিরোনাম',
                'sort_order'  => 2,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_hero_description',
                'value'       => 'সত্য প্রকাশ এবং চরমপন্থা ও সাম্প্রদায়িকতার বিরুদ্ধে মানুষকে সচেতন করাই আমাদের লক্ষ্য।',
                'label'       => 'হিরো সেকশন বিবরণ',
                'type'        => 'textarea',
                'group'       => 'about',
                'placeholder' => 'হিরো সেকশনের বিবরণ লিখুন',
                'help_text'   => 'এবাউট পেজের হিরো সেকশনের বিবরণ',
                'sort_order'  => 3,
                'is_active'   => true,
            ],
            [
                'key'         => 'about_why_items',
                'value'       => json_encode([
                    ['icon' => 'fa-users', 'title' => 'শান্তির বাণী', 'description' => 'মানুষের মধ্যে সম্প্রীতি প্রতিষ্ঠা করা', 'color' => '#017e3d'],
                    ['icon' => 'fa-shield-alt', 'title' => 'জঙ্গিবাদ প্রতিরোধ', 'description' => 'চরমপন্থা ও উগ্রবাদের বিরুদ্ধে সামাজিক সচেতনতা সৃষ্টি', 'color' => '#2563eb'],
                    ['icon' => 'fa-book-open', 'title' => 'মুক্ত সাহিত্য প্রচার', 'description' => 'মানুষকে সঠিক জ্ঞান দিতে বই ও গবেষণাপত্র ছড়িয়ে দেওয়া', 'color' => '#f59e0b'],
                    ['icon' => 'fa-headset', 'title' => 'সহযোগিতা', 'description' => 'যেকোনো মানবিক কাজে সাধারণ মানুষের পাশে দাঁড়ানো', 'color' => '#8b5cf6']
                ], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT),
                'label'       => 'কেন আমাদের বেছে নেবেন (JSON)',
                'type'        => 'json',
                'group'       => 'about',
                'placeholder' => '[{"icon": "fa-users", "title": "শান্তির বাণী", "description": "...", "color": "#017e3d"}]',
                'help_text'   => 'কেন বেছে নেবেন কার্ডের তালিকা (JSON ফরম্যাটে)',
                'sort_order'  => 4,
                'is_active'   => true,
            ]
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
